// <auto-generated />
namespace Ark.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;

    [GeneratedCode("EntityFramework.Migrations", "6.1.2-31219")]
    public sealed partial class Contact : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Contact));

        string IMigrationMetadata.Id
        {
            get { return "201506251431305_Contact"; }
        }

        string IMigrationMetadata.Source
        {
            get { return null; }
        }

        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
